// PrecomputedChebyshevData.cpp
// Auto-generated precomputed Chebyshev coefficients
// This file includes the .dat files generated by generate_chebyshev_data
// DO NOT EDIT MANUALLY

#include "PrecomputedChebyshevData.h"

namespace PrecomputedCheby {

// cpREV45
const VVVdouble cpREV45_coff = {
#include "../includes/../chebyshevData/cpREV45_coff.cheby.dat"
};
const VVVdouble cpREV45_derv_coff = {
#include "../includes/../chebyshevData/cpREV45_derv_coff.cheby.dat"
};
const VVVdouble cpREV45_sec_derv_coff = {
#include "../includes/../chebyshevData/cpREV45_sec_derv_coff.cheby.dat"
};

// dayhoff
const VVVdouble dayhoff_coff = {
#include "../includes/../chebyshevData/dayhoff_coff.cheby.dat"
};
const VVVdouble dayhoff_derv_coff = {
#include "../includes/../chebyshevData/dayhoff_derv_coff.cheby.dat"
};
const VVVdouble dayhoff_sec_derv_coff = {
#include "../includes/../chebyshevData/dayhoff_sec_derv_coff.cheby.dat"
};

// jones (JTT)
const VVVdouble jones_coff = {
#include "../includes/../chebyshevData/jones_coff.cheby.dat"
};
const VVVdouble jones_derv_coff = {
#include "../includes/../chebyshevData/jones_derv_coff.cheby.dat"
};
const VVVdouble jones_sec_derv_coff = {
#include "../includes/../chebyshevData/jones_sec_derv_coff.cheby.dat"
};

// mtREV24
const VVVdouble mtREV24_coff = {
#include "../includes/../chebyshevData/mtREV24_coff.cheby.dat"
};
const VVVdouble mtREV24_derv_coff = {
#include "../includes/../chebyshevData/mtREV24_derv_coff.cheby.dat"
};
const VVVdouble mtREV24_sec_derv_coff = {
#include "../includes/../chebyshevData/mtREV24_sec_derv_coff.cheby.dat"
};

// wag
const VVVdouble wag_coff = {
#include "../includes/../chebyshevData/wag_coff.cheby.dat"
};
const VVVdouble wag_derv_coff = {
#include "../includes/../chebyshevData/wag_derv_coff.cheby.dat"
};
const VVVdouble wag_sec_derv_coff = {
#include "../includes/../chebyshevData/wag_sec_derv_coff.cheby.dat"
};

// HIVb
const VVVdouble HIVb_coff = {
#include "../includes/../chebyshevData/HIVb_coff.cheby.dat"
};
const VVVdouble HIVb_derv_coff = {
#include "../includes/../chebyshevData/HIVb_derv_coff.cheby.dat"
};
const VVVdouble HIVb_sec_derv_coff = {
#include "../includes/../chebyshevData/HIVb_sec_derv_coff.cheby.dat"
};

// HIVw
const VVVdouble HIVw_coff = {
#include "../includes/../chebyshevData/HIVw_coff.cheby.dat"
};
const VVVdouble HIVw_derv_coff = {
#include "../includes/../chebyshevData/HIVw_derv_coff.cheby.dat"
};
const VVVdouble HIVw_sec_derv_coff = {
#include "../includes/../chebyshevData/HIVw_sec_derv_coff.cheby.dat"
};

// lg
const VVVdouble lg_coff = {
#include "../includes/../chebyshevData/lg_coff.cheby.dat"
};
const VVVdouble lg_derv_coff = {
#include "../includes/../chebyshevData/lg_derv_coff.cheby.dat"
};
const VVVdouble lg_sec_derv_coff = {
#include "../includes/../chebyshevData/lg_sec_derv_coff.cheby.dat"
};

// NOTE: empiriCodon skipped (codon model with 61 states, not 20)

// EX_BURIED
const VVVdouble EX_BURIED_coff = {
#include "../includes/../chebyshevData/EX_BURIED_coff.cheby.dat"
};
const VVVdouble EX_BURIED_derv_coff = {
#include "../includes/../chebyshevData/EX_BURIED_derv_coff.cheby.dat"
};
const VVVdouble EX_BURIED_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_BURIED_sec_derv_coff.cheby.dat"
};

// EX_EXPOSED
const VVVdouble EX_EXPOSED_coff = {
#include "../includes/../chebyshevData/EX_EXPOSED_coff.cheby.dat"
};
const VVVdouble EX_EXPOSED_derv_coff = {
#include "../includes/../chebyshevData/EX_EXPOSED_derv_coff.cheby.dat"
};
const VVVdouble EX_EXPOSED_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EXPOSED_sec_derv_coff.cheby.dat"
};

// EHO_EXTENDED
const VVVdouble EHO_EXTENDED_coff = {
#include "../includes/../chebyshevData/EHO_EXTENDED_coff.cheby.dat"
};
const VVVdouble EHO_EXTENDED_derv_coff = {
#include "../includes/../chebyshevData/EHO_EXTENDED_derv_coff.cheby.dat"
};
const VVVdouble EHO_EXTENDED_sec_derv_coff = {
#include "../includes/../chebyshevData/EHO_EXTENDED_sec_derv_coff.cheby.dat"
};

// EHO_HELIX
const VVVdouble EHO_HELIX_coff = {
#include "../includes/../chebyshevData/EHO_HELIX_coff.cheby.dat"
};
const VVVdouble EHO_HELIX_derv_coff = {
#include "../includes/../chebyshevData/EHO_HELIX_derv_coff.cheby.dat"
};
const VVVdouble EHO_HELIX_sec_derv_coff = {
#include "../includes/../chebyshevData/EHO_HELIX_sec_derv_coff.cheby.dat"
};

// EHO_OTHER
const VVVdouble EHO_OTHER_coff = {
#include "../includes/../chebyshevData/EHO_OTHER_coff.cheby.dat"
};
const VVVdouble EHO_OTHER_derv_coff = {
#include "../includes/../chebyshevData/EHO_OTHER_derv_coff.cheby.dat"
};
const VVVdouble EHO_OTHER_sec_derv_coff = {
#include "../includes/../chebyshevData/EHO_OTHER_sec_derv_coff.cheby.dat"
};

// EX_EHO_BUR_EXT
const VVVdouble EX_EHO_BUR_EXT_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_EXT_coff.cheby.dat"
};
const VVVdouble EX_EHO_BUR_EXT_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_EXT_derv_coff.cheby.dat"
};
const VVVdouble EX_EHO_BUR_EXT_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_EXT_sec_derv_coff.cheby.dat"
};

// EX_EHO_BUR_HEL
const VVVdouble EX_EHO_BUR_HEL_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_HEL_coff.cheby.dat"
};
const VVVdouble EX_EHO_BUR_HEL_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_HEL_derv_coff.cheby.dat"
};
const VVVdouble EX_EHO_BUR_HEL_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_HEL_sec_derv_coff.cheby.dat"
};

// EX_EHO_BUR_OTH
const VVVdouble EX_EHO_BUR_OTH_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_OTH_coff.cheby.dat"
};
const VVVdouble EX_EHO_BUR_OTH_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_OTH_derv_coff.cheby.dat"
};
const VVVdouble EX_EHO_BUR_OTH_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_BUR_OTH_sec_derv_coff.cheby.dat"
};

// EX_EHO_EXP_EXT
const VVVdouble EX_EHO_EXP_EXT_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_EXT_coff.cheby.dat"
};
const VVVdouble EX_EHO_EXP_EXT_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_EXT_derv_coff.cheby.dat"
};
const VVVdouble EX_EHO_EXP_EXT_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_EXT_sec_derv_coff.cheby.dat"
};

// EX_EHO_EXP_HEL
const VVVdouble EX_EHO_EXP_HEL_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_HEL_coff.cheby.dat"
};
const VVVdouble EX_EHO_EXP_HEL_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_HEL_derv_coff.cheby.dat"
};
const VVVdouble EX_EHO_EXP_HEL_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_HEL_sec_derv_coff.cheby.dat"
};

// EX_EHO_EXP_OTH
const VVVdouble EX_EHO_EXP_OTH_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_OTH_coff.cheby.dat"
};
const VVVdouble EX_EHO_EXP_OTH_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_OTH_derv_coff.cheby.dat"
};
const VVVdouble EX_EHO_EXP_OTH_sec_derv_coff = {
#include "../includes/../chebyshevData/EX_EHO_EXP_OTH_sec_derv_coff.cheby.dat"
};

} // namespace PrecomputedCheby
