# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and release Phylolib static library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  release_tag:
    runs-on: [ubuntu-latest]
    steps:
    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      date_tag: ${{ steps.generate_release_tag.outputs.release_tag }}

  build:
    needs: release_tag
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        create_package: "ON"
        package_generator: "ZIP"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.release_tag.outputs.date_tag }}
        name: Release ${{ needs.release_tag.outputs.date_tag }}
        files: build/*.tar.gz